name: chaos_kitchen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  fixnum: ^1.1.1
  flame: ^1.33.0
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  http: ^1.5.0
  protobuf: ^5.1.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/food/
    - assets/images/players/
