[project]
name = "chaos_kitchen_server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.120.3",
    "protobuf>=6.33.0",
    "websockets>=15.0.1",
]
